# Generated by Django 3.2.7 on 2021-10-01 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_scraper', '0002_auto_20211001_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchitem',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
