# Generated by Django 3.2.7 on 2021-10-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_scraper', '0003_alter_searchitem_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
